Controllers/DoctorController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using ReferralManagementSystem.Models;
using ReferralManagementSystem.Repository;
using ReferralManagementSystem.Repository.IRepository;
using ReferralManagementSystem.Utilities;

namespace ReferralManagementSystem.Controllers
{
    [AuthorizeRole("2")]
    public class DoctorController : Controller
    {
        private readonly IDoctorRepository _doctorRepository;
        public DoctorController(IDoctorRepository doctorRepository)
        {

            _doctorRepository = doctorRepository;
        }
        public IActionResult Index()
        {
            var doctorDetail = _doctorRepository.GetDoctorDetails();
            return View(doctorDetail);
        }
        [HttpGet]
        public IActionResult Create() => View();
        [HttpPost]
        public IActionResult Create(DoctorDetails doctorDetails)
        {
        //model state chek
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }
            _doctorRepository.CreateDoctorDetail(doctorDetails);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var data = _doctorRepository.GetDoctorDetails().FirstOrDefault(where => where.Id == id);
            return View(data);
        }
        [HttpPost]
        public IActionResult Edit(DoctorDetails doctorDetails)
        {
            _doctorRepository.UpdateDoctorDetail(doctorDetails);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            var data = _doctorRepository.GetDoctorDetails().FirstOrDefault(where => where.Id == id);
            return View(data);
        }
        [HttpPost]
        public IActionResult Delete(DoctorDetails doctorDetails)
        {
            _doctorRepository.DeleteDoctorDetail(doctorDetails);
            return RedirectToAction("Index");
        }
    }
}

Controllers/HospitalController.cs
using Microsoft.AspNetCore.Mvc;
using ReferralManagementSystem.Models;
using ReferralManagementSystem.Repository;
using ReferralManagementSystem.Repository.IRepository;
using ReferralManagementSystem.Utilities;

namespace ReferralManagementSystem.Controllers
{
    [AuthorizeRole("2")]
    public class HospitalController : Controller
    {
        private readonly IReferralHospitalDetailRepository _referralHospitalDetailRepository;
        public HospitalController(IReferralHospitalDetailRepository referralHospitalDetailRepository)
        {

            _referralHospitalDetailRepository = referralHospitalDetailRepository;
        }
        public async Task<IActionResult> Index()
        {
            var hospitalDetail = await _referralHospitalDetailRepository.GetHospitalAsync();
            return View(hospitalDetail);
        }

        [HttpGet]
        public IActionResult Create() => View();
        [HttpPost]
        public async Task<IActionResult> Create(ReferralHospitalDetail referralHospitalDetail)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }
            await _referralHospitalDetailRepository.CreateHospitalAsync(referralHospitalDetail);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var data = await _referralHospitalDetailRepository.GetHospitalAsync();
            var hospitalById = data.Find(x => x.Id == id);
            return View(hospitalById);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(ReferralHospitalDetail referralHospitalDetail)
        {
            await _referralHospitalDetailRepository.UpdateHospitalAsync(referralHospitalDetail);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var data = await _referralHospitalDetailRepository.GetHospitalAsync();
            var hospitalById = data.Find(x => x.Id == id);
            return View(hospitalById);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(ReferralHospitalDetail referralHospitalDetail)
        {
            await _referralHospitalDetailRepository.DeleteHospitalAsync(referralHospitalDetail);
            return RedirectToAction("Index");
        }
    }
}

Controllers/PatientRFController.cs
using Castle.MicroKernel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ReferralManagementSystem.Models;
using ReferralManagementSystem.Repository;
using ReferralManagementSystem.Repository.IRepository;
using ReferralManagementSystem.Utilities;

namespace ReferralManagementSystem.Controllers
{
    [AuthorizeRole("1")]
    public class PatientRFController : Controller
    {
        private readonly IPatientReferralFormRepository _patientReferralFormRepository;
        private readonly IReferralHospitalDetailRepository _referralHospitalDetailRepository;
        private readonly IDoctorRepository _doctorRepository;
        private readonly IUsersRepository _usersRepository;

        public PatientRFController(IPatientReferralFormRepository patientReferralFormRepository, IReferralHospitalDetailRepository referralHospitalDetailRepository, IDoctorRepository doctorRepository, IUsersRepository usersRepository)
        {

            _patientReferralFormRepository = patientReferralFormRepository;
            _referralHospitalDetailRepository = referralHospitalDetailRepository;
            _doctorRepository = doctorRepository;
            _usersRepository = usersRepository;
        }
        public async Task<IActionResult> Index()
        {
            var patientRFDetail = await _patientReferralFormRepository.GetPatientRFDetailsAsync();
            var activePatient = patientRFDetail.Where(x => x.IsActive == true).ToList();
            return View(activePatient);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var refferelHosptialDetail = await _referralHospitalDetailRepository.GetHospitalAsync();
            ViewBag.RefferelHospitalDetail = new SelectList(refferelHosptialDetail, "Id", "Name");

            var doctorDetail = _doctorRepository.GetDoctorDetails();
            ViewBag.DoctorDetail = new SelectList(doctorDetail, "Id", "Name");

            var userDetail = await _usersRepository.GetUsersDetailsAsync();
            ViewBag.UserDetail = new SelectList(userDetail, "Id", "Username");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(PatientReferralForm patientReferralForm)
        {
        //if Role is not mapped in model class then no need here to remove modelstate for role
            //ModelState.Remove("Role");
            
            if (!ModelState.IsValid)
            {
                var refferelHosptialDetail = await _referralHospitalDetailRepository.GetHospitalAsync();
                ViewBag.RefferelHospitalDetail = new SelectList(refferelHosptialDetail, "Id", "Name");
                
                var doctorDetail = _doctorRepository.GetDoctorDetails();
                ViewBag.DoctorDetail = new SelectList(doctorDetail, "Id", "Name");

                var userDetail = await _usersRepository.GetUsersDetailsAsync();
                ViewBag.UserDetail = new SelectList(userDetail, "Id", "Username");

                return View(patientReferralForm);
            }
            await _patientReferralFormRepository.CreatePatientRFAsync(patientReferralForm);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var refferelHosptialDetail = await _referralHospitalDetailRepository.GetHospitalAsync();
            ViewBag.RefferelHospitalDetail = new SelectList(refferelHosptialDetail, "Id", "Name");

            var doctorDetail = _doctorRepository.GetDoctorDetails();
            ViewBag.DoctorDetail = new SelectList(doctorDetail, "Id", "Name");

            var userDetail = await _usersRepository.GetUsersDetailsAsync();
            ViewBag.UserDetail = new SelectList(userDetail, "Id", "Username");

            var dataById = await _patientReferralFormRepository.GetPatientRFIdAsync(id);
            return View(dataById);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(PatientReferralForm patientReferralForm)
        {
            if (!ModelState.IsValid)
            {
                var refferelHosptialDetail = await _referralHospitalDetailRepository.GetHospitalAsync();
                ViewBag.RefferelHospitalDetail = new SelectList(refferelHosptialDetail, "Id", "Name");

                var doctorDetail = _doctorRepository.GetDoctorDetails();
                ViewBag.DoctorDetail = new SelectList(doctorDetail, "Id", "Name");

                var userDetail = await _usersRepository.GetUsersDetailsAsync();
                ViewBag.UserDetail = new SelectList(userDetail, "Id", "Username");

                return View(patientReferralForm);
            }

            await _patientReferralFormRepository.UpdatePatientRFAsync(patientReferralForm);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var data = await _patientReferralFormRepository.GetPatientRFIdAsync(id);
            
            return View(data);
        }
        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            await _patientReferralFormRepository.DeletePatientRFAsync(id);
            return RedirectToAction("Index");
        }
    }
}

Controllers/UserController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ReferralManagementSystem.Models;
using ReferralManagementSystem.Repository;
using ReferralManagementSystem.Repository.IRepository;
using ReferralManagementSystem.Utilities;

namespace ReferralManagementSystem.Controllers
{
    [AuthorizeRole("2")]
    public class UserController : Controller
    {
        private readonly IUsersRepository _usersRepository;
        private readonly IRolesRepository _rolesRepository;
      

        public UserController(IUsersRepository usersRepository, IRolesRepository rolesRepository)
        {
            _usersRepository = usersRepository;
            _rolesRepository = rolesRepository;
           
        }
        public async Task<IActionResult> Index()
        {
            var data= await _usersRepository.GetUsersDetailsAsync();
            return View(data);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var roles =  _rolesRepository.GetRoles();
            ViewBag.Roles = new SelectList(roles, "Id", "RoleName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Users users, IFormFile picture)
        {
            if (ModelState.IsValid)
            {
                await _usersRepository.CreateUserAsync(users, picture);
               return RedirectToAction("Index");
            }
            var roles = _rolesRepository.GetRoles();
            ViewBag.Roles = new SelectList(roles, "Id", "RoleName");
            return View(users);

           
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id, IFormFile picture)
        {
          
          var userId = await _usersRepository.GetUserByIdAsync(id);
            var roles = _rolesRepository.GetRoles();
            ViewBag.Roles = new SelectList(roles, "Id", "RoleName",userId.RoleId);
            return View(userId);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Users users, IFormFile picture)
        {
            if (!ModelState.IsValid)
            {
                var roles =  _rolesRepository.GetRoles();
                ViewBag.Roles = new SelectList(roles, "Id", "RoleName", users.RoleId);
                return View(users);
            }

            await _usersRepository.UpdateUserAsync(users,picture);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {

            var userId = await _usersRepository.GetUserByIdAsync(id);
            var roles = _rolesRepository.GetRoles();
            ViewBag.Roles = new SelectList(roles, "Id", "RoleName", userId.RoleId);
            return View(userId);
        }
        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _usersRepository.DeleteUserAsync(id);
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ReferralManagementSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ReferralManagementSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ReferralManagementSystem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        @if (new[] { "1", "2" }.Contains(Context.Session.GetString("Role")))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="PatientRF" asp-action="Index">Patient Referral Detail</a>
                            </li>
                        }

                        @if (Context.Session.GetString("Role") == "2")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Doctor" asp-action="Index">Doctor List</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Hospital" asp-action="Index">Hospital List</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users List</a>
                            </li>
                        }

                        @if (new[] { "1", "2" }.Contains(Context.Session.GetString("Role")))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        }
                    </ul>

                    @if (new[] { "1", "2" }.Contains(Context.Session.GetString("Role")))
                    {
                        <ul class="navbar-nav ms-auto">
                            <li class="nav-item">
                                <label class="nav-link text-dark">Hello, Mr. @ViewBag.Username.ToUpper()</label>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - ReferralManagementSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>